### ISSUE TITLE
Is version 1.21.7 supported?

### ISSUE THREAD

**Issue by pil0lo** [YesSteveModel/YSM-Wiki-Issues#257]
No matter what I tried, the mod didn’t work on the Fabric server for version 1.21.6.
Are you no longer updating it?
I’m really curious.

This mod is great, but I can’t use it because it isn’t updated when Minecraft gets a new version.
It’s truly disappointing.

Please make it available for version 1.21.7.
Soon, version 1.21.8 will be released as well.
I hope you will continue to update the mod so it works with each new version.

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'spellbladenext' at 'com.cleannrooster.spellblades.SpellbladesAndSuch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.cleannrooster.spellblades.SpellbladesAndSuch
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: mod/azure/azurelib/common/api/common/animatable/GeoItem [in thread "Render thread"]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.cleannrooster.spellblades.items.Items.orb(Items.java:116)
	at com.cleannrooster.spellblades.items.Items.orb(Items.java:112)
	at com.cleannrooster.spellblades.items.Items.<clinit>(Items.java:118)
	at com.cleannrooster.spellblades.items.loot.Default.<clinit>(Default.java:18)
	at com.cleannrooster.spellblades.SpellbladesAndSuch.<clinit>(SpellbladesAndSuch.java:161)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:71)
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:79)
	at net.minecraft.class_310.handler$fhd000$supermartijn642corelib$beforeInit(class_310.java:22671)
	... 5 more
